# Generated by Django 5.0.6 on 2024-05-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='inbound_entries',
            field=models.ManyToManyField(blank=True, null=True, related_name='inbound_entries_customuser', to='users.inbound'),
        ),
    ]
