# Generated by Django 5.0.6 on 2024-05-19 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_inbound_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_SKUs_expired', models.CharField(blank=True, max_length=255, null=True)),
                ('total_expired_SKUS_disposed', models.CharField(blank=True, max_length=255, null=True)),
                ('nearly_expired_1_to_3_months', models.CharField(blank=True, max_length=255, null=True)),
                ('nearly_expired_3_to_6_months', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_data', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_received_from_npco', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_orders', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_order_not_yet_picked', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_orders_picked_but_not_yet_ready_for_disptch_in_progress', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_orders_waiting_for_mod_qc', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_orders_that_are_ready_for_dispatch', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_orders_that_are_delivered_today', models.CharField(blank=True, max_length=255, null=True)),
                ('justification_for_the_delay_order_by_order', models.CharField(blank=True, max_length=255, null=True)),
                ('total_skus_picked', models.CharField(blank=True, max_length=255, null=True)),
                ('total_dash_of_SKU_discripancy_in_Order', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_PODs_collected_on_time', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_PODs_collected_Late', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_data', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders_items_returned', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_return_items_orders_updated_on_time', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_return_items_orders_updated_late', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_data', to='users.customuser')),
            ],
        ),
    ]
