# Generated by Django 5.0.6 on 2024-05-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_expiry_outbound_returns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dash_SKUs_Audited_in_Inventory', models.CharField(blank=True, max_length=255, null=True)),
                ('dash_of_SKUs_with_discripancy', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_QTYs_Damaged_by_WH', models.CharField(blank=True, max_length=255, null=True)),
                ('Number_of_Damaged_during_receiving', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Damaged_QTYs_Disposed', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_data', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Locations_Audited', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Locations_with_Incorrect_SKU_and_Qty', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_SKUs_Reconciliation', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_data', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PalletLocationAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Storage_Pallet', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Storage_Bin', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Storage_pallet_empty', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Storage_Bin_empty', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_occupied_pallet_location', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_occupied_pallet_locaiton2', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_location_availability_data', to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='TravelDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_no_of_Customers_deliverd', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_no_of_Pallet_deliverd', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_distance_data', to='users.customuser')),
            ],
        ),
    ]
