# Generated by Django 5.0.6 on 2024-05-21 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_damage_inventory_palletlocationavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='Total_No_of_Employees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='total_quantities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='HSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Incidents_on_the_side', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hse_data', to='users.customuser')),
            ],
        ),
    ]
