# Generated by Django 5.0.6 on 2024-05-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_owner_total_no_of_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ASN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ASN_Appointment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ASN_Status',
            field=models.CharField(choices=[('...', '...'), ('RGA', 'RGA'), ('Delivered', 'Delivered'), ('Approved', 'Approved'), ('New', 'New'), ('Return', 'Return'), ('Re-ASN', 'Re-ASN'), ('Rejected', 'Rejected'), ('Issue', 'Issue'), ('Not Delivered', 'Not Delivered'), ('Under RGA', 'Under RGA')], default='....', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Date_of_OLD_ASN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='GRN_ASN',
            field=models.CharField(choices=[('...', '...'), ('GR Issued', 'GR Issued'), ('Not Delivered', 'Not Delivered'), ('Physically Received', 'Physically Received'), ('N/A', 'N/A')], default='....', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='INVOICE',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Issue',
            field=models.CharField(choices=[('...', '...'), ('PO Expiry Date', 'PO Expiry Date'), ('Appointment canceled from NUPCO', 'Appointment canceled from NUPCO'), ('ASN QTY Mismatch', 'ASN QTY Mismatch'), ('Size of item', 'Size of item'), ('Ship to Location', 'Ship to Location'), ('Warehouse Transfer', 'Warehouse Transfer'), ('Transportation issue', 'Transportation issue'), ('Wrong/Missing Information', 'Wrong/Missing Information'), ('Short Notice Approval from Nupco', 'Short Notice Approval from Nupco'), ('Dispatch request before PO Due Date (early)', 'Dispatch request before PO Due Date (early)'), ('Annual Cycle Count', 'Annual Cycle Count'), ('QTY Issue', 'QTY Issue'), ('Shipment closed/not visible on NUPCO portal', 'Shipment closed/not visible on NUPCO portal'), ('Invoice Issue', 'Invoice Issue'), ('PO Issue', 'PO Issue'), ('Short shelf life of item', 'Short shelf life of item'), ('NUPCO Deleted some lines from the ASN', 'NUPCO Deleted some lines from the ASN'), ('Eninvoicing Issue', 'Eninvoicing Issue')], default='....', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='OBD',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='OLD_ASN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='OLD_ASN_Status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='OU',
            field=models.CharField(choices=[('...', '...'), ('Surgical Innovation', 'Surgical Innovation'), ('Patient Monitoring', 'Patient Monitoring'), ('Respiratory Interventions', 'Respiratory Interventions'), ('ENT', 'ENT'), ('Neurovascular', 'Neurovascular'), ('Endovenous', 'Endovenous'), ('Coronary', 'Coronary'), ('FOC', 'FOC'), ('WM', 'WM')], default='....', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='PGI_Date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='PO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='POD',
            field=models.CharField(choices=[('...', '...'), ('CN', 'CN'), ('POD', 'POD')], default='....', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Q',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Remark_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Ship_to_Location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Shipment_dash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
