# Generated by Django 5.0.6 on 2024-05-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_asn_customuser_asn_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Remark',
            new_name='Remark_1',
        ),
    ]
