# Generated by Django 5.0.6 on 2024-07-08 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=10)),
                ('total_available_locations_and_accupied', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantities', models.IntegerField(blank=True, null=True)),
                ('total_no_of_employees', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=10)),
                ('number_of_vehicles_daily', models.IntegerField(blank=True, null=True)),
                ('number_of_pallets', models.IntegerField(blank=True, null=True)),
                ('bulk', models.IntegerField(blank=True, null=True)),
                ('mix', models.IntegerField(blank=True, null=True)),
                ('cold', models.IntegerField(blank=True, null=True)),
                ('frozen', models.IntegerField(blank=True, null=True)),
                ('ambient', models.IntegerField(blank=True, null=True)),
                ('pending_shipments', models.IntegerField(blank=True, null=True)),
                ('no_of_shipments', models.IntegerField(blank=True, null=True)),
                ('admin_data', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.admindata')),
            ],
        ),
        migrations.CreateModel(
            name='AdminInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=10)),
                ('last_movement', models.IntegerField(blank=True, null=True)),
                ('admin_data', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.admindata')),
            ],
        ),
        migrations.CreateModel(
            name='AdminOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=10)),
                ('tender', models.IntegerField(blank=True, null=True)),
                ('private', models.IntegerField(blank=True, null=True)),
                ('lines', models.IntegerField(blank=True, null=True)),
                ('total_quantities', models.IntegerField(blank=True, null=True)),
                ('bulk', models.IntegerField(blank=True, null=True)),
                ('loose', models.IntegerField(blank=True, null=True)),
                ('pending_orders', models.IntegerField(blank=True, null=True)),
                ('admin_data', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.admindata')),
            ],
        ),
        migrations.CreateModel(
            name='AdminReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=10)),
                ('no_of_return', models.IntegerField(blank=True, null=True)),
                ('no_of_lines', models.IntegerField(blank=True, null=True)),
                ('total_quantities', models.IntegerField(blank=True, null=True)),
                ('admin_data', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.admindata')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_business', models.CharField(max_length=255)),
                ('employees', models.ManyToManyField(blank=True, related_name='admin_data_accessible_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'Employee')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_employees', to='administration.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Capacity',
        ),
        migrations.DeleteModel(
            name='Inbound',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Outbound',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Returns',
        ),
        migrations.AddField(
            model_name='admincapacity',
            name='admin_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.admindata'),
        ),
        migrations.AddField(
            model_name='admindata',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.company'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
