# Generated by Django 5.0.6 on 2024-05-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_inbound_no_of_shipments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='no_of_shipments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='number_of_pallets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='number_of_vehicles_daily',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='pending_shipments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
