# Generated by Django 5.0.6 on 2024-10-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_admincapacity_admindata_admininbound_admininventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininbound',
            name='number_of_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admininbound',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
