# Generated by Django 5.0.6 on 2024-10-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_admininbound_number_of_line_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admininbound',
            old_name='mix',
            new_name='loose',
        ),
    ]
