# Generated by Django 5.0.6 on 2024-05-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_inbound_no_of_shipments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound',
            name='shipment_type_ambient',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='shipment_type_bulk',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='shipment_type_cold',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='shipment_type_frozen',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='shipment_type_mix',
        ),
        migrations.AddField(
            model_name='inbound',
            name='ambient',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbound',
            name='bulk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbound',
            name='cold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbound',
            name='frozen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbound',
            name='mix',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
