# Generated by Django 5.0.6 on 2024-05-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_remove_inbound_shipment_type_ambient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbound',
            name='no_of_lines',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='no_of_orders_private',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='no_of_orders_tender',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='order_type_bulk',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='order_type_loose',
        ),
        migrations.AddField(
            model_name='outbound',
            name='bulk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='lines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='loose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='private',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outbound',
            name='tender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='pending_orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='total_quantities',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
