# Generated by Django 5.0.6 on 2024-10-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_rename_mix_admininbound_loose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admininbound',
            old_name='no_of_shipments',
            new_name='number_of_shipments',
        ),
    ]
