# Generated by Django 5.0.6 on 2024-10-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_rename_no_of_shipments_admininbound_number_of_shipments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admincapacity',
            old_name='total_available_locations_and_accupied',
            new_name='WH_storage',
        ),
        migrations.AddField(
            model_name='admincapacity',
            name='available_location',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admincapacity',
            name='occupied_location',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
