# Generated by Django 5.0.6 on 2024-05-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_outbound_no_of_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='hc_business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
