# Generated by Django 5.0.6 on 2024-05-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_owner_hc_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='Total_No_of_Employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='total_quantities',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
