# Generated by Django 5.0.6 on 2024-10-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_rename_total_available_locations_and_accupied_admincapacity_wh_storage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminreturns',
            old_name='no_of_lines',
            new_name='number_of_lines',
        ),
        migrations.RenameField(
            model_name='adminreturns',
            old_name='no_of_return',
            new_name='number_of_return',
        ),
    ]
