# Generated by Django 5.0.6 on 2024-05-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_admindata_delete_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='total_available_locations_and_accupied',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
