# Generated by Django 5.0.6 on 2024-05-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_capacity_total_available_locations_and_accupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='no_of_lines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returns',
            name='no_of_return',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returns',
            name='total_quantities',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
