# Generated by Django 5.0.6 on 2024-05-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_returns_no_of_lines_alter_returns_no_of_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='last_movement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
