# Generated by Django 5.0.6 on 2024-05-31 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_inventory_last_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='admin_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='administration.admindata'),
            preserve_default=False,
        ),
    ]
