# Generated by Django 5.0.6 on 2024-06-01 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_inbound_admin_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='admin_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.admindata'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='admin_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.admindata'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='admin_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.admindata'),
        ),
        migrations.AddField(
            model_name='returns',
            name='admin_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.admindata'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='admin_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.admindata'),
        ),
    ]
