# Generated by Django 5.0.6 on 2024-06-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_capacity_admin_data_inventory_admin_data_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Capacity',
            new_name='AdminCapacity',
        ),
        migrations.RenameModel(
            old_name='Inbound',
            new_name='AdminInbound',
        ),
        migrations.RenameModel(
            old_name='Inventory',
            new_name='AdminInventory',
        ),
        migrations.RenameModel(
            old_name='Outbound',
            new_name='AdminOutbound',
        ),
        migrations.RenameModel(
            old_name='Returns',
            new_name='AdminReturns',
        ),
    ]
