# Generated by Django 5.0.6 on 2024-07-01 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_rename_capacity_admincapacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='accessible_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
