# Generated by Django 5.0.6 on 2024-07-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_alter_admindata_employees_adminemployeeprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminEmployeeProfile',
        ),
    ]
