# Generated by Django 5.0.6 on 2024-05-27 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dash_SKUs_Audited_in_Inventory', models.CharField(blank=True, max_length=255, null=True)),
                ('dash_of_SKUs_with_discripancy', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_QTYs_Damaged_by_WH', models.CharField(blank=True, max_length=255, null=True)),
                ('Number_of_Damaged_during_receiving', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Damaged_QTYs_Disposed', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_SKUs_expired', models.CharField(blank=True, max_length=255, null=True)),
                ('total_expired_SKUS_disposed', models.CharField(blank=True, max_length=255, null=True)),
                ('nearly_expired_1_to_3_months', models.CharField(blank=True, max_length=255, null=True)),
                ('nearly_expired_3_to_6_months', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Incidents_on_the_side', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Locations_Audited', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Locations_with_Incorrect_SKU_and_Qty', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_SKUs_Reconciliation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_received_from_npco', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_orders', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_order_not_yet_picked', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_orders_picked_but_not_yet_ready_for_disptch_in_progress', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_orders_waiting_for_mod_qc', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_orders_that_are_ready_for_dispatch', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_orders_that_are_delivered_today', models.CharField(blank=True, max_length=255, null=True)),
                ('justification_for_the_delay_order_by_order', models.CharField(blank=True, max_length=255, null=True)),
                ('total_skus_picked', models.CharField(blank=True, max_length=255, null=True)),
                ('total_dash_of_SKU_discripancy_in_Order', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_PODs_collected_on_time', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_PODs_collected_Late', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PalletLocationAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Storage_Pallet', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Storage_Bin', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Storage_pallet_empty', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_Storage_Bin_empty', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_occupied_pallet_location', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_occupied_pallet_locaiton2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders_items_returned', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_return_items_orders_updated_on_time', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_return_items_orders_updated_late', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_no_of_Customers_deliverd', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_no_of_Pallet_deliverd', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=10)),
                ('total_shipments_in_asn', models.CharField(blank=True, max_length=255, null=True)),
                ('arrived', models.CharField(blank=True, max_length=255, null=True)),
                ('no_show', models.CharField(blank=True, max_length=255, null=True)),
                ('received_completely', models.CharField(blank=True, max_length=255, null=True)),
                ('regected_completely', models.CharField(blank=True, max_length=255, null=True)),
                ('received_partially', models.CharField(blank=True, max_length=255, null=True)),
                ('under_tamer_inspection', models.CharField(blank=True, max_length=255, null=True)),
                ('waiting_for_mod_inspection', models.CharField(blank=True, max_length=255, null=True)),
                ('waiting_for_NUPCO_action', models.CharField(blank=True, max_length=255, null=True)),
                ('total_dash_of_GR_reports_shared', models.CharField(blank=True, max_length=255, null=True)),
                ('dash_of_GR_reports_with_discripancy', models.CharField(blank=True, max_length=255, null=True)),
                ('total_SKUS_received', models.CharField(blank=True, max_length=255, null=True)),
                ('dash_of_skus_damaged_during_receiving', models.CharField(blank=True, max_length=255, null=True)),
                ('total_received_with_putaway', models.CharField(blank=True, max_length=255, null=True)),
                ('OBD', models.CharField(blank=True, max_length=255, null=True)),
                ('INVOICE', models.CharField(blank=True, max_length=255, null=True)),
                ('PO', models.CharField(blank=True, max_length=255, null=True)),
                ('OU', models.CharField(choices=[('...', '...'), ('Surgical Innovation', 'Surgical Innovation'), ('Patient Monitoring', 'Patient Monitoring'), ('Respiratory Interventions', 'Respiratory Interventions'), ('ENT', 'ENT'), ('Neurovascular', 'Neurovascular'), ('Endovenous', 'Endovenous'), ('Coronary', 'Coronary'), ('FOC', 'FOC'), ('WM', 'WM')], default='....', max_length=255)),
                ('Ship_to_Location', models.CharField(blank=True, max_length=255, null=True)),
                ('Shipment_dash', models.CharField(blank=True, max_length=255, null=True)),
                ('PGI_Date', models.CharField(blank=True, max_length=255, null=True)),
                ('Q', models.CharField(blank=True, max_length=255, null=True)),
                ('ASN_Appointment', models.CharField(blank=True, max_length=255, null=True)),
                ('ASN', models.CharField(blank=True, max_length=255, null=True)),
                ('ASN_Status', models.CharField(choices=[('...', '...'), ('RGA', 'RGA'), ('Delivered', 'Delivered'), ('Approved', 'Approved'), ('New', 'New'), ('Return', 'Return'), ('Re-ASN', 'Re-ASN'), ('Rejected', 'Rejected'), ('Issue', 'Issue'), ('Not Delivered', 'Not Delivered'), ('Under RGA', 'Under RGA')], default='....', max_length=255)),
                ('POD', models.CharField(choices=[('...', '...'), ('CN', 'CN'), ('POD', 'POD')], default='....', max_length=255)),
                ('GRN_ASN', models.CharField(choices=[('...', '...'), ('GR Issued', 'GR Issued'), ('Not Delivered', 'Not Delivered'), ('Physically Received', 'Physically Received'), ('N/A', 'N/A')], default='....', max_length=255)),
                ('OLD_ASN', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_of_OLD_ASN', models.CharField(blank=True, max_length=255, null=True)),
                ('OLD_ASN_Status', models.CharField(blank=True, max_length=255, null=True)),
                ('Issue', models.CharField(choices=[('...', '...'), ('PO Expiry Date', 'PO Expiry Date'), ('Appointment canceled from NUPCO', 'Appointment canceled from NUPCO'), ('ASN QTY Mismatch', 'ASN QTY Mismatch'), ('Size of item', 'Size of item'), ('Ship to Location', 'Ship to Location'), ('Warehouse Transfer', 'Warehouse Transfer'), ('Transportation issue', 'Transportation issue'), ('Wrong/Missing Information', 'Wrong/Missing Information'), ('Short Notice Approval from Nupco', 'Short Notice Approval from Nupco'), ('Dispatch request before PO Due Date (early)', 'Dispatch request before PO Due Date (early)'), ('Annual Cycle Count', 'Annual Cycle Count'), ('QTY Issue', 'QTY Issue'), ('Shipment closed/not visible on NUPCO portal', 'Shipment closed/not visible on NUPCO portal'), ('Invoice Issue', 'Invoice Issue'), ('PO Issue', 'PO Issue'), ('Short shelf life of item', 'Short shelf life of item'), ('NUPCO Deleted some lines from the ASN', 'NUPCO Deleted some lines from the ASN'), ('Eninvoicing Issue', 'Eninvoicing Issue')], default='....', max_length=255)),
                ('Remark_1', models.CharField(blank=True, max_length=255, null=True)),
                ('Remark_2', models.CharField(blank=True, max_length=255, null=True)),
                ('inbound_entries', models.ManyToManyField(blank=True, related_name='inbound_entries_customuser', to='customer.inbound')),
            ],
        ),
    ]
