# Generated by Django 5.0.6 on 2024-07-01 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('Total_QTYs_Damaged_by_WH', models.IntegerField(blank=True, null=True)),
                ('Number_of_Damaged_during_receiving', models.IntegerField(blank=True, null=True)),
                ('Total_Damaged_QTYs_Disposed', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('total_SKUs_expired', models.IntegerField(blank=True, null=True)),
                ('total_expired_SKUS_disposed', models.IntegerField(blank=True, null=True)),
                ('nearly_expired_1_to_3_months', models.IntegerField(blank=True, null=True)),
                ('nearly_expired_3_to_6_months', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiries', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('Total_Incidents_on_the_side', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hses', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('total_shipments_in_asn', models.IntegerField(blank=True, null=True)),
                ('arrived', models.IntegerField(blank=True, null=True)),
                ('no_show', models.IntegerField(blank=True, null=True)),
                ('received_completely', models.IntegerField(blank=True, null=True)),
                ('rejected_completely', models.IntegerField(blank=True, null=True)),
                ('received_partially', models.IntegerField(blank=True, null=True)),
                ('under_tamer_inspection', models.IntegerField(blank=True, null=True)),
                ('waiting_for_mod_inspection', models.IntegerField(blank=True, null=True)),
                ('waiting_for_NUPCO_action', models.IntegerField(blank=True, null=True)),
                ('total_dash_of_GR_reports_shared', models.IntegerField(blank=True, null=True)),
                ('dash_of_GR_reports_with_discripancy', models.IntegerField(blank=True, null=True)),
                ('total_SKUS_received', models.IntegerField(blank=True, null=True)),
                ('dash_of_skus_damaged_during_receiving', models.IntegerField(blank=True, null=True)),
                ('total_received_with_putaway', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('Total_Locations_Audited', models.IntegerField(blank=True, null=True)),
                ('Total_Locations_with_Incorrect_SKU_and_Qty', models.IntegerField(blank=True, null=True)),
                ('Total_SKUs_Reconciliation', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('order_received_from_npco', models.IntegerField(blank=True, null=True)),
                ('pending_orders', models.IntegerField(blank=True, null=True)),
                ('number_of_order_not_yet_picked', models.IntegerField(blank=True, null=True)),
                ('number_of_orders_picked_but_not_yet_ready_for_disptch_in_progress', models.IntegerField(blank=True, null=True)),
                ('number_of_orders_waiting_for_mod_qc', models.IntegerField(blank=True, null=True)),
                ('number_of_orders_that_are_ready_for_dispatch', models.IntegerField(blank=True, null=True)),
                ('number_of_orders_that_are_delivered_today', models.IntegerField(blank=True, null=True)),
                ('justification_for_the_delay_order_by_order', models.IntegerField(blank=True, null=True)),
                ('total_skus_picked', models.IntegerField(blank=True, null=True)),
                ('total_dash_of_SKU_discripancy_in_Order', models.IntegerField(blank=True, null=True)),
                ('number_of_PODs_collected_on_time', models.IntegerField(blank=True, null=True)),
                ('number_of_PODs_collected_Late', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbounds', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPalletLocationAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('Total_Storage_Pallet', models.IntegerField(blank=True, null=True)),
                ('Total_Storage_Bin', models.IntegerField(blank=True, null=True)),
                ('Total_Storage_pallet_empty', models.IntegerField(blank=True, null=True)),
                ('Total_Storage_Bin_empty', models.IntegerField(blank=True, null=True)),
                ('Total_occupied_pallet_location', models.IntegerField(blank=True, null=True)),
                ('Total_occupied_Bin_location', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_location_availabilities', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('total_orders_items_returned', models.IntegerField(blank=True, null=True)),
                ('number_of_return_items_orders_updated_on_time', models.IntegerField(blank=True, null=True)),
                ('number_of_return_items_orders_updated_late', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTravelDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('Total_no_of_Customers_deliverd', models.IntegerField(blank=True, null=True)),
                ('Total_no_of_Pallet_deliverd', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_distances', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'Employee')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='customer.customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
