# Generated by Django 5.0.6 on 2024-06-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound',
            name='inbound_entries',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='regected_completely',
        ),
        migrations.AddField(
            model_name='inbound',
            name='rejected_completely',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='OBD',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='arrived',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='dash_of_GR_reports_with_discripancy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='dash_of_skus_damaged_during_receiving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='no_show',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='received_completely',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='received_partially',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='total_SKUS_received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='total_dash_of_GR_reports_shared',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='total_received_with_putaway',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='total_shipments_in_asn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='under_tamer_inspection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='waiting_for_NUPCO_action',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='waiting_for_mod_inspection',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
