# Generated by Django 5.0.6 on 2024-07-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinbound',
            old_name='waiting_for_NUPCO_action',
            new_name='waiting_for_action',
        ),
        migrations.RenameField(
            model_name='customerinbound',
            old_name='waiting_for_mod_inspection',
            new_name='waiting_for_inspection',
        ),
        migrations.RenameField(
            model_name='customeroutbound',
            old_name='number_of_orders_waiting_for_mod_qc',
            new_name='number_of_orders_waiting_for_qc',
        ),
    ]
