# Generated by Django 5.0.6 on 2024-06-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_company_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Damage',
            new_name='CustomerDamage',
        ),
        migrations.RenameModel(
            old_name='Expiry',
            new_name='CustomerExpiry',
        ),
        migrations.RenameModel(
            old_name='HSE',
            new_name='CustomerHSE',
        ),
        migrations.RenameModel(
            old_name='Inbound',
            new_name='CustomerInbound',
        ),
        migrations.RenameModel(
            old_name='Inventory',
            new_name='CustomerInventory',
        ),
        migrations.RenameModel(
            old_name='Outbound',
            new_name='CustomerOutbound',
        ),
        migrations.RenameModel(
            old_name='PalletLocationAvailability',
            new_name='CustomerPalletLocationAvailability',
        ),
        migrations.RenameModel(
            old_name='Returns',
            new_name='CustomerReturns',
        ),
        migrations.RenameModel(
            old_name='TravelDistance',
            new_name='CustomerTravelDistance',
        ),
    ]
