# Generated by Django 5.0.6 on 2024-06-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_inbound_inbound_entries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='OBD',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
