# Generated by Django 5.0.6 on 2024-10-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_no_show_customerinbound_not_arrived_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinbound',
            old_name='dash_of_GR_reports_with_discripancy',
            new_name='number_of_GR_reports_with_discripancy',
        ),
        migrations.RenameField(
            model_name='customerinbound',
            old_name='total_dash_of_GR_reports_shared',
            new_name='total_number_of_GR_reports_shared',
        ),
    ]
