# Generated by Django 5.0.6 on 2024-06-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_damage_customerdamage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
