# Generated by Django 5.0.6 on 2024-10-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_number_of_orders_that_are_delivered_today_customeroutbound_pending_pick_orders_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerTravelDistance',
        ),
    ]
