# Generated by Django 5.0.6 on 2024-10-07 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_delete_customertraveldistance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customertransportationoutbound',
            old_name='Total_no_of_Customers_deliverd',
            new_name='justification_for_the_delay_order_by_order',
        ),
        migrations.RenameField(
            model_name='customertransportationoutbound',
            old_name='Total_no_of_Pallet_deliverd',
            new_name='number_of_PODs_collected_Late',
        ),
        migrations.AddField(
            model_name='customertransportationoutbound',
            name='number_of_PODs_collected_on_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransportationoutbound',
            name='number_of_order_not_yet_picked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransportationoutbound',
            name='number_of_orders_picked_but_not_yet_ready_for_disptch_in_progress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransportationoutbound',
            name='number_of_orders_that_are_ready_for_dispatch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransportationoutbound',
            name='number_of_orders_waiting_for_qc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransportationoutbound',
            name='pending_pick_orders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransportationoutbound',
            name='piked_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransportationoutbound',
            name='released_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransportationoutbound',
            name='total_dash_of_SKU_discripancy_in_Order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertransportationoutbound',
            name='total_skus_picked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customertransportationoutbound',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbounds', to='customer.customer'),
        ),
        migrations.DeleteModel(
            name='CustomerOutbound',
        ),
    ]
