# Generated by Django 5.0.6 on 2024-10-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_rename_total_dash_of_sku_discripancy_in_order_customerwhoutbound_total_number_of_sku_discripancy_in_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdamage',
            old_name='Total_Damaged_QTYs_Disposed',
            new_name='Total_Araive_Damaged',
        ),
    ]
