# Generated by Django 5.0.6 on 2024-10-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_rename_total_damaged_qtys_disposed_customerdamage_total_araive_damaged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinbound',
            old_name='arrived',
            new_name='ambient',
        ),
        migrations.RenameField(
            model_name='customerinbound',
            old_name='not_arrived',
            new_name='bulk',
        ),
        migrations.RenameField(
            model_name='customerinbound',
            old_name='number_of_GR_reports_with_discripancy',
            new_name='cold',
        ),
        migrations.RenameField(
            model_name='customerinbound',
            old_name='number_of_skus_damaged_during_receiving',
            new_name='frozen',
        ),
        migrations.RenameField(
            model_name='customerinbound',
            old_name='received_completely',
            new_name='loose',
        ),
        migrations.RenameField(
            model_name='customerinbound',
            old_name='received_partially',
            new_name='number_of_line',
        ),
        migrations.RenameField(
            model_name='customerinbound',
            old_name='rejected_completely',
            new_name='number_of_pallets',
        ),
        migrations.RenameField(
            model_name='customerinbound',
            old_name='total_SKUS_received',
            new_name='number_of_shipments',
        ),
        migrations.RenameField(
            model_name='customerinbound',
            old_name='total_number_of_GR_reports_shared',
            new_name='number_of_vehicles_daily',
        ),
        migrations.RenameField(
            model_name='customerinbound',
            old_name='total_received_with_putaway',
            new_name='pending_shipments',
        ),
        migrations.RenameField(
            model_name='customerinbound',
            old_name='under_tamer_inspection',
            new_name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='customerinbound',
            name='waiting_for_action',
        ),
        migrations.RemoveField(
            model_name='customerinbound',
            name='waiting_for_inspection',
        ),
        migrations.AlterField(
            model_name='customerinbound',
            name='assigned_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
