# Generated by Django 5.0.6 on 2024-10-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_rename_arrived_customerinbound_ambient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertransportationoutbound',
            name='justification_for_the_delay_order_by_order',
        ),
        migrations.RemoveField(
            model_name='customertransportationoutbound',
            name='number_of_order_not_yet_picked',
        ),
        migrations.RemoveField(
            model_name='customertransportationoutbound',
            name='number_of_orders_picked_but_not_yet_ready_for_disptch_in_progress',
        ),
        migrations.RemoveField(
            model_name='customertransportationoutbound',
            name='number_of_orders_that_are_ready_for_dispatch',
        ),
        migrations.RemoveField(
            model_name='customertransportationoutbound',
            name='number_of_orders_waiting_for_qc',
        ),
        migrations.RemoveField(
            model_name='customertransportationoutbound',
            name='total_number_of_SKU_discripancy_in_Order',
        ),
        migrations.RemoveField(
            model_name='customertransportationoutbound',
            name='total_skus_picked',
        ),
        migrations.RemoveField(
            model_name='customerwhoutbound',
            name='justification_for_the_delay_order_by_order',
        ),
        migrations.RemoveField(
            model_name='customerwhoutbound',
            name='number_of_order_not_yet_picked',
        ),
        migrations.RemoveField(
            model_name='customerwhoutbound',
            name='number_of_orders_picked_but_not_yet_ready_for_disptch_in_progress',
        ),
        migrations.RemoveField(
            model_name='customerwhoutbound',
            name='number_of_orders_that_are_ready_for_dispatch',
        ),
        migrations.RemoveField(
            model_name='customerwhoutbound',
            name='number_of_orders_waiting_for_qc',
        ),
        migrations.RemoveField(
            model_name='customerwhoutbound',
            name='total_number_of_SKU_discripancy_in_Order',
        ),
        migrations.RemoveField(
            model_name='customerwhoutbound',
            name='total_skus_picked',
        ),
    ]
