# Generated by Django 5.0.6 on 2024-07-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_hierarchicalgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HierarchicalGroup',
        ),
    ]
